baseurl: '/'
permalink: pretty
title: valanticLT

logo:
  mobile: "images/logo/logo-mobile.svg"
  mobile_height: "20px"
  mobile_width: "100px"
  desktop: "images/logo/logo.svg"
  desktop_height: "20px"
  desktop_width: "100px"

home: 
  limit_services: 6

collections:
  operate:
    output: true
    sort_by: weight
  strength:
    output: true
    sort_by: weight
  process:
    output: true
    sort_by: weight
  team:
    output: true
    sort_by: weight

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
